<a href="https://colab.research.google.com/github/manikcb/sem_project/blob/main/sample7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
import numpy as np

In [2]:
# Load Iris Data
iris = datasets.load_iris()

In [3]:
# Split dataset into features and target variable
X = iris.data  
y = iris.target

In [4]:

import xgboost as xgb
print(xgb.__version__)

0.90


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100, stratify=y)

In [6]:
X_train.shape

(120, 4)

In [ ]:
bt = xgb.XGBClassifier(
    max_depth=5, learning_rate=0.2, n_estimators=10, objective="multi:softmax"
)  # Setup xgboost model
bt.fit(X_train, y_train, verbose=False)  # Train it to our data

In [8]:
# Predict and compare with real labels
bt.predict(X_test)

array([1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 0, 1, 0, 0, 1, 2, 1])

In [9]:

y_test

array([1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 0, 2, 0, 0, 2, 2, 1])

In [10]:
model_file_name = "DEMO-local-xgboost-model"

# Save model using Booster  - Problem with predict ('numpy.ndarray' object has no attribute 'feature_names')
#bt._Booster.save_model(model_file_name)

# Save model using sklearn XGBClassifier API - Problem with predict ('XGBClassifier' object has no attribute '_le')
#bt.save_model(model_file_name)


# Save model using pickle - Recommended according to https://github.com/dmlc/xgboost/pull/3829
# Use joblib which is considered better than pickling 
import joblib
joblib.dump(bt, model_file_name) 

['DEMO-local-xgboost-model']

In [11]:
import numpy as np

point_X = X_test[0:5]

print(point_X)

#point_X = np.expand_dims(point_X, axis=0)
#print(point_X)
#point_y = test_y[0]

np.savetxt("test_point.csv", point_X, delimiter=",")

[[5.4 3.  4.5 1.5]
 [5.6 3.  4.1 1.3]
 [6.3 2.8 5.1 1.5]
 [6.  3.  4.8 1.8]
 [5.1 3.3 1.7 0.5]]


In [12]:
file_name = (
    "test_point.csv"  # customize to your test file, will be 'mnist.single.test' if use data above
)

with open(file_name, "r") as f:
    mypayload = np.loadtxt(f, delimiter=",")

print(mypayload)

[[5.4 3.  4.5 1.5]
 [5.6 3.  4.1 1.3]
 [6.3 2.8 5.1 1.5]
 [6.  3.  4.8 1.8]
 [5.1 3.3 1.7 0.5]]


In [13]:
bt1 = joblib.load(model_file_name)
bt1.predict(mypayload)

array([1, 1, 1, 2, 0])